### ISSUE TITLE
Could not open the database: mkdir /var/lib/happydomain/db/: permission denied

### ISSUE THREAD

**Issue by skapytek** [happyDomain/happydomain#30]
Hi,

tried to create a docker container with this settings for my yaml:

```
version: '3.5'
services:
    happydomain:
        ports:
            - '8492:8081'
        volumes:
            - ./config/happydomain.conf:/etc/happydomain.conf
            - ./var:/var/lib/happydomain:rw
        restart: always
        environment:
            - HAPPYDOMAIN_mail-smtp-host=mysmtp.domain.tld
            - HAPPYDOMAIN_mail-smtp-port=587
            - HAPPYDOMAIN_mail-from=myemailusername
            - HAPPYDOMAIN_MAIL_SMTP_PASSWORD=mypassword
            - HAPPYDOMAIN_LEVELDB_PATH=/var/lib/happydomain/db/
        image: happydomain/happydomain
```

Im getting this error message in the log and i dont know how to solve this:

`2024/09/07 19:28:28 Could not open the database: mkdir /var/lib/happydomain/db/: permission denied`

**Comment by nemunaire** [comment]
Hi @skapytek!

The happyDomain container is rootless by default, so interacting with volumes from the host system creates permissions issues as your `./var` directory is owned by your user (or root) on the host. The container uses the user-id 15353, which is definitely not the same as your user-id on your host. This situation leads to the permission denied you faced.

You can fix this by running the container [as your user-id](https://docs.docker.com/reference/compose-file/services/#user):

```yaml
services:
    happydomain:
        ...
        user: ${UID}
```

or as root:


```yaml
services:
    happydomain:
        ...
        user: root
```

Another solution is to force the ownership of your `./var` directory to the happyDomain's user-id:
```sh
sudo chown 15353 ./var
```
